### ISSUE TITLE
Add Google Analytics 

### ISSUE THREAD

**Issue by hassanabidpk** [MOOCCircle/codeforeveryone#12]
<script type="text/javascript">
!function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.0.1";
analytics.load("st84JOhemrqvWhw6f3XEsQ23wR1ORRcz");
analytics.page()
}}();
</script>

**Comment by jinpark** [comment]
I suggest https://segment.com/ on top of GA

**Comment by hassanabidpk** [comment]
added

**Comment by jinpark** [comment]
Wheres the PR/commit?

**Comment by hassanabidpk** [comment]
https://github.com/MOOCCircle/codeforeveryone/commit/598f13c8179a0fc8870acc0677ccf52c36e438ce

**Comment by jinpark** [comment]
Thanks!
