### ISSUE TITLE
Remove links from navbar until they actually go somewhere

### ISSUE THREAD

**Issue by jinpark** [MOOCCircle/codeforeveryone#9]
Probably just commenting them out should be fine

@veroniquecho or @RachellCalhoun should be able to do this easily :)

Let me know if you need any help

**Comment by veroniquecho** [comment]
i can't navigate on github! where is the page i gotta fix...? :( it's my first time on github.....

**Comment by hassanabidpk** [comment]
fixed

**Comment by jinpark** [comment]
Wheres the PR/commit?

**Comment by hassanabidpk** [comment]
https://github.com/MOOCCircle/codeforeveryone/commit/598f13c8179a0fc8870acc0677ccf52c36e438ce

**Comment by jinpark** [comment]
Looks good in prod
